<html>
<body>
<table>
<tr><td>Container</td><td><input type='text' readonly="1" style='width: 50px' name='cheque_container[]'></td><td><input type='text' style='width: 50px' name='cheque_container[]'></td><td><input type='text' style='width: 50px' name='cheque_container[]'></td><td><input type='text' style='width: 50px' name='cheque_container[]'></td><td><input type='text' style='width: 50px' name='cheque_container[]'></td><td><input type='text' style='width: 50px' name='cheque_container[]'></td><td><input type='text' style='width: 50px' name='cheque_container[]'></td><td><input type='text' style='width: 50px' name='cheque_container[]'></td><td><input type='text' style='width: 50px' name='cheque_container[]'></td><td><input type='text' style='width: 50px' name='cheque_container[]'></td></tr>
<tr><td>Size</td><td><input type='text' style='width: 50px' name='cheque_size[]'></td><td><input type='text' style='width: 50px' name='cheque_size[]'></td><td><input type='text' style='width: 50px' name='cheque_size[]'></td><td><input type='text' style='width: 50px' name='cheque_size[]'></td><td><input type='text' style='width: 50px' name='cheque_size[]'></td><td><input type='text' style='width: 50px' name='cheque_size[]'></td><td><input type='text' style='width: 50px' name='cheque_size[]'></td><td><input type='text' style='width: 50px' name='cheque_size[]'></td><td><input type='text' style='width: 50px' name='cheque_size[]'></td><td><input type='text' style='width: 50px' name='cheque_size[]'></td></tr>
<tr><td>Arrival Date</td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td><td><input type='text' style='width: 50px' name='cheque_ardate[]'></td></tr>
<tr><td>Empty Return Date</td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td><td><input type='text' style='width: 50px' name='cheque_retdate[]'></td></tr>
<tr><td>Days</td><td><input type='text' style='width: 50px' name='cheque_days[]'></td><td><input type='text' style='width: 50px' name='cheque_days[]'></td><td><input type='text' style='width: 50px' name='cheque_days[]'></td><td><input type='text' style='width: 50px' name='cheque_days[]'></td><td><input type='text' style='width: 50px' name='cheque_days[]'></td><td><input type='text' style='width: 50px' name='cheque_days[]'></td><td><input type='text' style='width: 50px' name='cheque_days[]'></td><td><input type='text' style='width: 50px' name='cheque_days[]'></td><td><input type='text' style='width: 50px' name='cheque_days[]'></td><td><input type='text' style='width: 50px' name='cheque_days[]'></td></tr>
<tr><td>Det Amount</td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td><td><input type='text' style='width: 50px' name='cheque_detamount[]'></td></tr>
</table>
</body>
</html>
