version: '3.9'

services:
  php:
    container_name: ${APP_NAME}_php
    build:
      args:
        user: www-data
        group: www-data
        uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    working_dir: /var/www/html/
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    ports:
      - 8080:80
    volumes:
      - ./docker/app/:/var/www/html/
      - ./docker/php:/usr/local/etc/php/custom.d
    networks:
      net:
        ipv4_address: ${NETWORK}.6

  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}_mysql
    restart: always
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - "5306:3306"
    volumes:
      - ./docker/mysql/lib:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/logs:/var/log/mysql
    #user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    networks:
      net:
        ipv4_address: ${NETWORK}.7

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK}.0/24
