TYPE=VIEW
query=select `tirtash_db`.`xxuser_group`.`xgroupid` AS `xgroupid`,`tirtash_db`.`xxuser_group`.`xgroup` AS `xgroup` from `tirtash_db`.`xxuser_group`
md5=aabac00a3fc024e41c322691bdb6533b
updatable=1
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2022-08-09 19:10:07
create-version=1
source=select `xxuser_group`.`xgroupid` AS `xgroupid`,`xxuser_group`.`xgroup` AS `xgroup` from `xxuser_group`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `tirtash_db`.`xxuser_group`.`xgroupid` AS `xgroupid`,`tirtash_db`.`xxuser_group`.`xgroup` AS `xgroup` from `tirtash_db`.`xxuser_group`
