TYPE=VIEW
query=select `tirtash_db`.`xxcontainer`.`xcontainerid` AS `xcontainerid`,`tirtash_db`.`xxcontainer`.`xcarrierid` AS `xcarrierid`,`tirtash_db`.`xxcontainer`.`xcontainernumber` AS `xcontainernumber`,`tirtash_db`.`xxcontainer`.`xcontainertypeid` AS `xcontainertypeid`,`tirtash_db`.`xxcontainer`.`xcontainersizeid` AS `xcontainersizeid`,`tirtash_db`.`xxcontainertype`.`xcontainertype` AS `xcontainertype`,`tirtash_db`.`xxcontainersize`.`xcontainersize` AS `xcontainersize`,`tirtash_db`.`xxcontainer`.`xown` AS `xown`,`tirtash_db`.`xxcontainer`.`xcompanycontainer` AS `xcompanycontainer`,`tirtash_db`.`xxcarrier`.`xcarrier` AS `xcarrier`,`tirtash_db`.`xxcarrier`.`xcarriertype` AS `xcarriertype`,`tirtash_db`.`xxcarrier`.`xphone` AS `xphone`,`tirtash_db`.`xxcarrier`.`xfax` AS `xfax`,`tirtash_db`.`xxcarrier`.`xmanager` AS `xmanager`,`tirtash_db`.`xxcarrier`.`xmanagerphone` AS `xmanagerphone`,`tirtash_db`.`xxcarrier`.`xresponsible` AS `xresponsible`,`tirtash_db`.`xxcarrier`.`xresponsiblephone` AS `xresponsiblephone`,`tirtash_db`.`xxcarrier`.`xaddress` AS `xaddress` from (((`tirtash_db`.`xxcontainer` left join `tirtash_db`.`xxcarrier` on((`tirtash_db`.`xxcontainer`.`xcarrierid` = `tirtash_db`.`xxcarrier`.`xcarrierid`))) left join `tirtash_db`.`xxcontainertype` on((`tirtash_db`.`xxcontainer`.`xcontainertypeid` = `tirtash_db`.`xxcontainertype`.`xcontainertypeid`))) left join `tirtash_db`.`xxcontainersize` on((`tirtash_db`.`xxcontainer`.`xcontainersizeid` = `tirtash_db`.`xxcontainersize`.`xcontainersizeid`)))
md5=1b66cde64ad47bab9936b818f206ba2b
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2022-08-09 19:10:07
create-version=1
source=select `xxcontainer`.`xcontainerid` AS `xcontainerid`,`xxcontainer`.`xcarrierid` AS `xcarrierid`,`xxcontainer`.`xcontainernumber` AS `xcontainernumber`,`xxcontainer`.`xcontainertypeid` AS `xcontainertypeid`,`xxcontainer`.`xcontainersizeid` AS `xcontainersizeid`,`xxcontainertype`.`xcontainertype` AS `xcontainertype`,`xxcontainersize`.`xcontainersize` AS `xcontainersize`,`xxcontainer`.`xown` AS `xown`,`xxcontainer`.`xcompanycontainer` AS `xcompanycontainer`,`xxcarrier`.`xcarrier` AS `xcarrier`,`xxcarrier`.`xcarriertype` AS `xcarriertype`,`xxcarrier`.`xphone` AS `xphone`,`xxcarrier`.`xfax` AS `xfax`,`xxcarrier`.`xmanager` AS `xmanager`,`xxcarrier`.`xmanagerphone` AS `xmanagerphone`,`xxcarrier`.`xresponsible` AS `xresponsible`,`xxcarrier`.`xresponsiblephone` AS `xresponsiblephone`,`xxcarrier`.`xaddress` AS `xaddress` from (((`xxcontainer` left join `xxcarrier` on((`xxcontainer`.`xcarrierid` = `xxcarrier`.`xcarrierid`))) left join `xxcontainertype` on((`xxcontainer`.`xcontainertypeid` = `xxcontainertype`.`xcontainertypeid`))) left join `xxcontainersize` on((`xxcontainer`.`xcontainersizeid` = `xxcontainersize`.`xcontainersizeid`)))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `tirtash_db`.`xxcontainer`.`xcontainerid` AS `xcontainerid`,`tirtash_db`.`xxcontainer`.`xcarrierid` AS `xcarrierid`,`tirtash_db`.`xxcontainer`.`xcontainernumber` AS `xcontainernumber`,`tirtash_db`.`xxcontainer`.`xcontainertypeid` AS `xcontainertypeid`,`tirtash_db`.`xxcontainer`.`xcontainersizeid` AS `xcontainersizeid`,`tirtash_db`.`xxcontainertype`.`xcontainertype` AS `xcontainertype`,`tirtash_db`.`xxcontainersize`.`xcontainersize` AS `xcontainersize`,`tirtash_db`.`xxcontainer`.`xown` AS `xown`,`tirtash_db`.`xxcontainer`.`xcompanycontainer` AS `xcompanycontainer`,`tirtash_db`.`xxcarrier`.`xcarrier` AS `xcarrier`,`tirtash_db`.`xxcarrier`.`xcarriertype` AS `xcarriertype`,`tirtash_db`.`xxcarrier`.`xphone` AS `xphone`,`tirtash_db`.`xxcarrier`.`xfax` AS `xfax`,`tirtash_db`.`xxcarrier`.`xmanager` AS `xmanager`,`tirtash_db`.`xxcarrier`.`xmanagerphone` AS `xmanagerphone`,`tirtash_db`.`xxcarrier`.`xresponsible` AS `xresponsible`,`tirtash_db`.`xxcarrier`.`xresponsiblephone` AS `xresponsiblephone`,`tirtash_db`.`xxcarrier`.`xaddress` AS `xaddress` from (((`tirtash_db`.`xxcontainer` left join `tirtash_db`.`xxcarrier` on((`tirtash_db`.`xxcontainer`.`xcarrierid` = `tirtash_db`.`xxcarrier`.`xcarrierid`))) left join `tirtash_db`.`xxcontainertype` on((`tirtash_db`.`xxcontainer`.`xcontainertypeid` = `tirtash_db`.`xxcontainertype`.`xcontainertypeid`))) left join `tirtash_db`.`xxcontainersize` on((`tirtash_db`.`xxcontainer`.`xcontainersizeid` = `tirtash_db`.`xxcontainersize`.`xcontainersizeid`)))
