TYPE=VIEW
query=select `tirtash_db`.`xxidentity`.`xidentityid` AS `xidentityid`,`tirtash_db`.`xxidentity`.`xpartyaccountid` AS `xpartyaccountid`,`tirtash_db`.`xxidentity`.`xpartyaccountetc` AS `xpartyaccountetc`,coalesce(`cr`.`xcarrier`,`of`.`xoffice`,concat(`cu`.`xname`,_utf8\' \',`cu`.`xfamily`)) AS `xpartyaccount`,`cr`.`xcarriertype` AS `xcarriertype`,coalesce(`cr`.`xphone`,`cu`.`xphone`,`of`.`xphone`) AS `xphone`,coalesce(`cr`.`xfax`,`cu`.`xfax`,`of`.`xfax`) AS `xfax`,`cr`.`xmanager` AS `xmanager`,`cr`.`xmanagerphone` AS `xmanagerphone`,`cr`.`xresponsible` AS `xresponsible`,`cr`.`xresponsiblephone` AS `xresponsiblephone`,coalesce(`cr`.`xaddress`,`cu`.`xaddress`,`of`.`xaddress`) AS `xaddress`,`cu`.`xgender` AS `xgender`,`cu`.`xcompany` AS `xcompany`,`cu`.`xpost` AS `xpost`,`cu`.`xcity` AS `xcity`,`cu`.`xcountryid` AS `xcountryid`,coalesce(`cu`.`xemail`,`of`.`xemail`) AS `xemail`,coalesce(`cu`.`xwebsite`,`of`.`xwebsite`) AS `xwebsite`,`cu`.`xdes` AS `xdes`,(case substr(`tirtash_db`.`xxidentity`.`xpartyaccountid`,1,3) when _utf8\'ofc\' then _utf8\'office\' when _utf8\'cst\' then _utf8\'customer\' when _utf8\'cri\' then _utf8\'carrier\' else _utf8\'etc\' end) AS `xtype` from (((`tirtash_db`.`xxidentity` left join `tirtash_db`.`xxoffice` `of` on((concat(_utf8\'ofc\',`of`.`xofficeid`) = `tirtash_db`.`xxidentity`.`xpartyaccountid`))) left join `tirtash_db`.`xxcustomer` `cu` on((concat(_utf8\'cst\',`cu`.`xcustomerid`) = `tirtash_db`.`xxidentity`.`xpartyaccountid`))) left join `tirtash_db`.`xxcarrier` `cr` on((concat(_utf8\'cri\',`cr`.`xcarrierid`) = `tirtash_db`.`xxidentity`.`xpartyaccountid`)))
md5=9d0867b8bb21a0f6ec7fb8ffb144d178
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2022-08-09 19:10:07
create-version=1
source=select `xxidentity`.`xidentityid` AS `xidentityid`,`xxidentity`.`xpartyaccountid` AS `xpartyaccountid`,`xxidentity`.`xpartyaccountetc` AS `xpartyaccountetc`,coalesce(`cr`.`xcarrier`,`of`.`xoffice`,concat(`cu`.`xname`,_utf8\' \',`cu`.`xfamily`)) AS `xpartyaccount`,`cr`.`xcarriertype` AS `xcarriertype`,coalesce(`cr`.`xphone`,`cu`.`xphone`,`of`.`xphone`) AS `xphone`,coalesce(`cr`.`xfax`,`cu`.`xfax`,`of`.`xfax`) AS `xfax`,`cr`.`xmanager` AS `xmanager`,`cr`.`xmanagerphone` AS `xmanagerphone`,`cr`.`xresponsible` AS `xresponsible`,`cr`.`xresponsiblephone` AS `xresponsiblephone`,coalesce(`cr`.`xaddress`,`cu`.`xaddress`,`of`.`xaddress`) AS `xaddress`,`cu`.`xgender` AS `xgender`,`cu`.`xcompany` AS `xcompany`,`cu`.`xpost` AS `xpost`,`cu`.`xcity` AS `xcity`,`cu`.`xcountryid` AS `xcountryid`,coalesce(`cu`.`xemail`,`of`.`xemail`) AS `xemail`,coalesce(`cu`.`xwebsite`,`of`.`xwebsite`) AS `xwebsite`,`cu`.`xdes` AS `xdes`,(case substr(`xxidentity`.`xpartyaccountid`,1,3) when _utf8\'ofc\' then _utf8\'office\' when _utf8\'cst\' then _utf8\'customer\' when _utf8\'cri\' then _utf8\'carrier\' else _utf8\'etc\' end) AS `xtype` from (((`xxidentity` left join `xxoffice` `of` on((concat(_utf8\'ofc\',`of`.`xofficeid`) = `xxidentity`.`xpartyaccountid`))) left join `xxcustomer` `cu` on((concat(_utf8\'cst\',`cu`.`xcustomerid`) = `xxidentity`.`xpartyaccountid`))) left join `xxcarrier` `cr` on((concat(_utf8\'cri\',`cr`.`xcarrierid`) = `xxidentity`.`xpartyaccountid`)))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `tirtash_db`.`xxidentity`.`xidentityid` AS `xidentityid`,`tirtash_db`.`xxidentity`.`xpartyaccountid` AS `xpartyaccountid`,`tirtash_db`.`xxidentity`.`xpartyaccountetc` AS `xpartyaccountetc`,coalesce(`cr`.`xcarrier`,`of`.`xoffice`,concat(`cu`.`xname`,\' \',`cu`.`xfamily`)) AS `xpartyaccount`,`cr`.`xcarriertype` AS `xcarriertype`,coalesce(`cr`.`xphone`,`cu`.`xphone`,`of`.`xphone`) AS `xphone`,coalesce(`cr`.`xfax`,`cu`.`xfax`,`of`.`xfax`) AS `xfax`,`cr`.`xmanager` AS `xmanager`,`cr`.`xmanagerphone` AS `xmanagerphone`,`cr`.`xresponsible` AS `xresponsible`,`cr`.`xresponsiblephone` AS `xresponsiblephone`,coalesce(`cr`.`xaddress`,`cu`.`xaddress`,`of`.`xaddress`) AS `xaddress`,`cu`.`xgender` AS `xgender`,`cu`.`xcompany` AS `xcompany`,`cu`.`xpost` AS `xpost`,`cu`.`xcity` AS `xcity`,`cu`.`xcountryid` AS `xcountryid`,coalesce(`cu`.`xemail`,`of`.`xemail`) AS `xemail`,coalesce(`cu`.`xwebsite`,`of`.`xwebsite`) AS `xwebsite`,`cu`.`xdes` AS `xdes`,(case substr(`tirtash_db`.`xxidentity`.`xpartyaccountid`,1,3) when \'ofc\' then \'office\' when \'cst\' then \'customer\' when \'cri\' then \'carrier\' else \'etc\' end) AS `xtype` from (((`tirtash_db`.`xxidentity` left join `tirtash_db`.`xxoffice` `of` on((concat(\'ofc\',`of`.`xofficeid`) = `tirtash_db`.`xxidentity`.`xpartyaccountid`))) left join `tirtash_db`.`xxcustomer` `cu` on((concat(\'cst\',`cu`.`xcustomerid`) = `tirtash_db`.`xxidentity`.`xpartyaccountid`))) left join `tirtash_db`.`xxcarrier` `cr` on((concat(\'cri\',`cr`.`xcarrierid`) = `tirtash_db`.`xxidentity`.`xpartyaccountid`)))
